### ISSUE TITLE
请问这个必须得是Linux平台嘛？

### ISSUE THREAD

**Issue by Sssssystem** [helloyoucan/cmsys#1]
请问这个必须得是Linux平台嘛？学校里的电脑是Windows7，请问能够使用嘛？

**Comment by helloyoucan** [comment]
哪个平台都可以，需要配置NodeJs环境，需要有node，npm的知识

**Comment by helloyoucan** [comment]
> 请问这个必须得是Linux平台嘛？学校里的电脑是Windows7，请问能够使用嘛？

都可以，需要node环境，node,npm的知识需要有。

**Comment by Sssssystem** [comment]
好的，谢谢(^-^)
